"""
fabric_connector.py
-------------------
Microsoft Fabric Data Warehouse connector.

Authentication order:
  1. notebookutils (inside a Fabric notebook — token is injected automatically)
  2. InteractiveBrowserCredential (local dev — opens a browser AAD login once,
     then caches the token in ~/.azure/)

Usage:
    from src.data_pipeline.fabric_connector import connect, fetch_eda_dataset

    conn = connect()
    df   = fetch_eda_dataset()
    conn.close()

Priceband classification
------------------------
Pricebands (Economy / Mid / Premium) are derived from actual MRP distribution
per category (not hardcoded). The pipeline runs in two steps:

  Step 1  fetch_mrp_distribution()
            - Runs _MRP_DIST_SQL against Fabric
            - Returns MRP percentiles per category

  Step 2  compute_priceband_breaks(mrp_df)
            - p33 -> Economy cap, p67 -> Mid cap, rounded to nearest Rs 500

  Step 3  fetch_eda_dataset(breaks)
            - Fetches style-level data via _EDA_SQL (no priceband in SQL)
            - Applies priceband classification in Python using the breaks dict
            - Aggregates to bucket level (store x category x priceband)
            - Returns bucket-level DataFrame identical to what the solver expects
"""

import json
import struct
from pathlib import Path

import pandas as pd
import pyodbc

WAREHOUSE_SERVER   = "t5fulvvcjsjehnrpedrb4vbtli-crzekx4zfiqutls4y4njjiwi3y.datawarehouse.fabric.microsoft.com"
WAREHOUSE_DATABASE = "Arvind_Analytics_Warehouse"


# ── Style-level EDA SQL ───────────────────────────────────────────────────────
# Outputs one row per store x style x category.
# Priceband classification is applied in Python using priceband_mapping.csv
# (generated by fetch_mrp_distribution + compute_priceband_breaks every Monday).
# This keeps the SQL simple and stable — priceband thresholds never appear in SQL.
_EDA_SQL = """
-- ============================================================
-- ARROW STORE REVENUE OPTIMISATION — STYLE-LEVEL EDA DATASET
-- Scope : Active Arrow stores | last 4 weeks
-- Grain : store x style x category
-- Note  : Priceband is applied in Python after this query runs,
--         using priceband_mapping.csv generated from MRP distribution.
-- Scans : FACT_FNO_SOH_DAILY + FACT_FNO_SALES_TC_ONLINE_BASE
-- ============================================================
WITH date_bounds AS (
    SELECT
        CONVERT(DATE, DATEADD(WEEK, -4, GETDATE())) AS window_start,
        CONVERT(DATE, GETDATE())                     AS window_end
),
active_arrow_stores AS (
    SELECT STORE_CODE, NAME_2 AS store_name
    FROM [Arvind_Analytics_Warehouse].[prd].[DIM_SAP_STORE_MASTER]
    WHERE ARROW  != 0
      AND STATUS  = 'ACTIVE'
),
sales_style AS (
    SELECT
        f.SAP_STORECODE                                AS store_id,
        f.STYLECODE                                    AS style_code,
        UPPER(LTRIM(RTRIM(f.CATEGORY)))               AS category,
        AVG(CAST(f.UNITMRP AS FLOAT))                 AS avg_unit_mrp,
        SUM(f.NETAMT)                                  AS style_revenue_4w,
        SUM(f.QUANTITY)                                AS style_units_sold,
        SUM(f.TOTAL_MRP)                               AS style_total_mrp,
        SUM(f.TOTAL_MRP - f.NETAMT)                    AS style_discount,
        COUNT(DISTINCT f.INVOICENO)                    AS style_transactions,
        COUNT(DISTINCT CONVERT(DATE, f.INVOICE_DATE)) AS style_days_with_sales
    FROM [Arvind_Analytics_Warehouse].[prd].[FACT_FNO_SALES_TC_ONLINE_BASE] f
    INNER JOIN active_arrow_stores st ON f.SAP_STORECODE = st.STORE_CODE
    CROSS JOIN date_bounds d
    WHERE f.BRAND          = 'ARROW'
      AND f.INVOICETYPE    = 'SALES'
      AND f.QUALITY        = 'Q1'
      AND f.QUANTITY       > 0
      AND UPPER(LTRIM(RTRIM(f.CATEGORY))) NOT IN (
            'PROMO', 'SAMPLES', 'SCRAP', 'TRIMS', 'CARRY BAG'
      )
      AND CONVERT(DATE, f.INVOICE_DATE) >= d.window_start
      AND CONVERT(DATE, f.INVOICE_DATE) <  d.window_end
    GROUP BY f.SAP_STORECODE, f.STYLECODE, UPPER(LTRIM(RTRIM(f.CATEGORY)))
),
soh_style AS (
    SELECT
        s.SAP_STORE_ID                                                                     AS store_id,
        s.STYLE_CODE                                                                       AS style_code,
        AVG(CAST(s.SOH AS FLOAT)) * 7                                                     AS style_avg_weekly_soh,
        SUM(CAST(s.SOH AS FLOAT))                                                         AS style_total_soh,
        MIN(s.SOH)                                                                         AS style_min_soh,
        MAX(s.SOH)                                                                         AS style_max_soh,
        COUNT(DISTINCT CONVERT(DATE, LEFT(CAST(s.LOAD_RUN_DATE AS VARCHAR), 8), 112))     AS style_soh_days
    FROM [Arvind_Analytics_Warehouse].[prd].[FACT_FNO_SOH_DAILY] s
    INNER JOIN active_arrow_stores st ON s.SAP_STORE_ID = st.STORE_CODE
    CROSS JOIN date_bounds d
    WHERE s.BRAND = 'ARROW'
      AND CONVERT(DATE, LEFT(CAST(s.LOAD_RUN_DATE AS VARCHAR), 8), 112) >= d.window_start
      AND CONVERT(DATE, LEFT(CAST(s.LOAD_RUN_DATE AS VARCHAR), 8), 112) <= d.window_end
    GROUP BY s.SAP_STORE_ID, s.STYLE_CODE
)
SELECT
    sl.store_id,
    st.store_name,
    sl.style_code,
    sl.category,
    sl.avg_unit_mrp,
    sl.style_revenue_4w,
    sl.style_units_sold,
    sl.style_total_mrp,
    sl.style_discount,
    sl.style_transactions,
    sl.style_days_with_sales,
    COALESCE(so.style_avg_weekly_soh, 0) AS style_avg_weekly_soh,
    COALESCE(so.style_total_soh,      0) AS style_total_soh,
    COALESCE(so.style_min_soh,        0) AS style_min_soh,
    COALESCE(so.style_max_soh,        0) AS style_max_soh,
    COALESCE(so.style_soh_days,       0) AS style_soh_days,
    d.window_start,
    d.window_end
FROM sales_style sl
INNER JOIN active_arrow_stores st ON st.STORE_CODE = sl.store_id
LEFT JOIN soh_style so ON so.store_id = sl.store_id AND so.style_code = sl.style_code
CROSS JOIN date_bounds d
ORDER BY sl.store_id, sl.category, sl.style_code;
"""


# ── MRP percentile discovery SQL ─────────────────────────────────────────────
# SQL Server: PERCENTILE_CONT requires OVER (PARTITION BY ...) — cannot be
# used as a plain GROUP BY aggregate. Split into:
#   raw         — filtered rows (category, stylecode, unitmrp)
#   percentiles — window-function percentiles per category, SELECT DISTINCT
#   counts      — COUNT DISTINCT / MIN / MAX via GROUP BY
# then JOIN counts and percentiles on category.
_MRP_DIST_SQL = """
WITH date_bounds AS (
    SELECT
        CONVERT(DATE, DATEADD(WEEK, -4, GETDATE())) AS window_start,
        CONVERT(DATE, GETDATE())                     AS window_end
),
active_arrow_stores AS (
    SELECT STORE_CODE
    FROM [Arvind_Analytics_Warehouse].[prd].[DIM_SAP_STORE_MASTER]
    WHERE ARROW != 0 AND STATUS = 'ACTIVE'
),
raw AS (
    SELECT
        UPPER(LTRIM(RTRIM(f.CATEGORY))) AS category,
        f.STYLECODE,
        f.UNITMRP
    FROM [Arvind_Analytics_Warehouse].[prd].[FACT_FNO_SALES_TC_ONLINE_BASE] f
    INNER JOIN active_arrow_stores st ON f.SAP_STORECODE = st.STORE_CODE
    CROSS JOIN date_bounds d
    WHERE f.BRAND       = 'ARROW'
      AND f.INVOICETYPE = 'SALES'
      AND UPPER(LTRIM(RTRIM(f.CATEGORY))) NOT IN (
            'PROMO', 'SAMPLES', 'SCRAP', 'TRIMS', 'CARRY BAG'
      )
      AND CONVERT(DATE, f.INVOICE_DATE) >= d.window_start
      AND CONVERT(DATE, f.INVOICE_DATE) <  d.window_end
),
percentiles AS (
    SELECT DISTINCT
        category,
        PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY UNITMRP) OVER (PARTITION BY category) AS p10,
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY UNITMRP) OVER (PARTITION BY category) AS p25,
        PERCENTILE_CONT(0.33) WITHIN GROUP (ORDER BY UNITMRP) OVER (PARTITION BY category) AS p33,
        PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY UNITMRP) OVER (PARTITION BY category) AS p50,
        PERCENTILE_CONT(0.67) WITHIN GROUP (ORDER BY UNITMRP) OVER (PARTITION BY category) AS p67,
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY UNITMRP) OVER (PARTITION BY category) AS p75,
        PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY UNITMRP) OVER (PARTITION BY category) AS p90
    FROM raw
),
counts AS (
    SELECT
        category,
        COUNT(DISTINCT STYLECODE) AS style_count,
        COUNT(*)                  AS transaction_rows,
        MIN(UNITMRP)              AS min_mrp,
        MAX(UNITMRP)              AS max_mrp
    FROM raw
    GROUP BY category
)
SELECT
    c.category,
    c.style_count,
    c.transaction_rows,
    c.min_mrp,
    c.max_mrp,
    p.p10,
    p.p25,
    p.p33,
    p.p50,
    p.p67,
    p.p75,
    p.p90
FROM counts c
INNER JOIN percentiles p ON p.category = c.category
ORDER BY c.style_count DESC;
"""


# ── Priceband computation ─────────────────────────────────────────────────────

def compute_priceband_breaks(mrp_dist_df: pd.DataFrame) -> dict:
    """
    Compute data-driven priceband break points from MRP percentile distribution.

    Strategy: tertile split using p33 (Economy cap) and p67 (Mid cap).
    Values are rounded to the nearest Rs 500 for clean, readable thresholds.

    Returns
    -------
    dict  {category: {"economy_cap": int, "mid_cap": int}, "_default": {...}}
    """
    breaks = {}
    for _, row in mrp_dist_df.iterrows():
        cat = row["category"]
        economy_cap = int(round(float(row["p33"]) / 500) * 500)
        mid_cap     = int(round(float(row["p67"]) / 500) * 500)
        economy_cap = max(economy_cap, 500)
        if mid_cap <= economy_cap:
            mid_cap = economy_cap + 500
        breaks[cat] = {"economy_cap": economy_cap, "mid_cap": mid_cap}

    breaks["_default"] = {"economy_cap": 2000, "mid_cap": 3000}
    return breaks


def _classify_priceband(mrp: float, economy_cap: int, mid_cap: int) -> str:
    if mrp <= economy_cap:
        return "Economy"
    elif mrp <= mid_cap:
        return "Mid"
    return "Premium"


def _apply_priceband(style_df: pd.DataFrame, breaks: dict) -> pd.DataFrame:
    """
    Add 'priceband' and 'bucket_key' columns to style-level DataFrame
    using per-category break points from the breaks dict.
    """
    df = style_df.copy()
    default = breaks.get("_default", {"economy_cap": 2000, "mid_cap": 3000})

    def classify(row):
        b = breaks.get(row["category"], default)
        return _classify_priceband(row["avg_unit_mrp"], b["economy_cap"], b["mid_cap"])

    df["priceband"]  = df.apply(classify, axis=1)
    df["bucket_key"] = df["category"] + " | " + df["priceband"]
    return df


def _aggregate_to_buckets(style_df: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate style-level data to bucket level (store x category x priceband).
    Computes all derived metrics (revenue_rate, sell_through_pct, signals, etc.)
    that the solver and Streamlit app need.
    """
    grp_cols = ["store_id", "store_name", "category", "priceband", "bucket_key"]
    grp = style_df.groupby(grp_cols)

    bucket = grp.agg(
        bucket_revenue_4w      = ("style_revenue_4w",    "sum"),
        units_sold_4w          = ("style_units_sold",    "sum"),
        total_mrp_4w           = ("style_total_mrp",     "sum"),
        total_discount_4w      = ("style_discount",      "sum"),
        transaction_count      = ("style_transactions",  "sum"),
        days_with_sales        = ("style_days_with_sales", "max"),
        avg_weekly_soh         = ("style_avg_weekly_soh", "sum"),
        total_soh_units        = ("style_total_soh",     "sum"),
        min_daily_soh          = ("style_min_soh",       "min"),
        max_daily_soh          = ("style_max_soh",       "max"),
        soh_snapshot_days      = ("style_soh_days",      "max"),
        style_count_in_bucket  = ("style_code",          "nunique"),
        window_start           = ("window_start",        "first"),
        window_end             = ("window_end",          "first"),
    ).reset_index()

    # Derived metrics
    bucket["discount_pct"] = (
        (bucket["total_discount_4w"] / bucket["total_mrp_4w"] * 100)
        .where(bucket["total_mrp_4w"] > 0)
        .round(1)
    )
    bucket["revenue_rate"] = (
        (bucket["bucket_revenue_4w"] / (bucket["avg_weekly_soh"] * 4))
        .where(bucket["avg_weekly_soh"] > 0)
        .round(2)
    )
    bucket["sell_through_pct"] = (
        (
            bucket["units_sold_4w"]
            / (bucket["total_soh_units"] + bucket["units_sold_4w"])
            * 100
        )
        .where(bucket["total_soh_units"] > 0)
        .round(1)
    )
    bucket["avg_basket_value"] = (
        (bucket["bucket_revenue_4w"] / bucket["transaction_count"])
        .where(bucket["transaction_count"] > 0)
        .round(0)
    )
    bucket["avg_daily_revenue"] = (
        (bucket["bucket_revenue_4w"] / bucket["days_with_sales"])
        .where(bucket["days_with_sales"] > 0)
        .round(0)
    )

    # Per-store p25/p75 for signal_preview
    valid = bucket[bucket["revenue_rate"].notna()]
    store_pcts = (
        valid.groupby("store_id")["revenue_rate"]
        .quantile([0.25, 0.75])
        .unstack()
        .rename(columns={0.25: "_p25", 0.75: "_p75"})
        .reset_index()
    )
    bucket = bucket.merge(store_pcts, on="store_id", how="left")

    bucket["signal_preview"] = bucket.apply(
        lambda r: (
            "NO SOH"   if r["avg_weekly_soh"] == 0 else
            "NO SALES" if pd.isna(r["revenue_rate"]) else
            "INCREASE" if r["revenue_rate"] >= r["_p75"] else
            "REDUCE"   if r["revenue_rate"] <= r["_p25"] else
            "HOLD"
        ),
        axis=1,
    )
    bucket = bucket.drop(columns=["_p25", "_p75"])

    # Solver readiness
    n_buckets = bucket.groupby("store_id")["bucket_key"].transform("count")
    bucket["active_buckets_in_store"] = n_buckets
    bucket["solver_readiness"] = n_buckets.map(
        lambda n: (
            "IDEAL"            if n < 20  else
            "GOOD"             if n < 50  else
            "LIMITED"          if n < 100 else
            "COARSEN REQUIRED"
        )
    )

    # Data quality
    bucket["data_quality_flag"] = bucket["days_with_sales"].apply(
        lambda d: (
            "NO SALES DATA"             if pd.isna(d) else
            "THIN — use category fallback" if d < 14 else
            "OK"
        )
    )

    return bucket


# ── Connection ────────────────────────────────────────────────────────────────

def _get_token() -> str:
    """Obtain an AAD bearer token for the Fabric warehouse."""
    try:
        import notebookutils  # available inside Fabric notebooks
        return notebookutils.credentials.getToken("https://database.windows.net/")
    except ImportError:
        pass
    from azure.identity import InteractiveBrowserCredential
    credential = InteractiveBrowserCredential()
    return credential.get_token("https://database.windows.net/.default").token


def connect() -> pyodbc.Connection:
    """Open an authenticated pyodbc connection to the Fabric warehouse."""
    token        = _get_token()
    token_bytes  = bytes(token, "UTF-16LE")
    token_struct = struct.pack(f"<I{len(token_bytes)}s", len(token_bytes), token_bytes)
    conn_str = (
        "Driver={ODBC Driver 18 for SQL Server};"
        f"Server={WAREHOUSE_SERVER},1433;"
        f"Database={WAREHOUSE_DATABASE};"
        "Encrypt=yes;"
        "TrustServerCertificate=no;"
    )
    return pyodbc.connect(conn_str, attrs_before={1256: token_struct}, autocommit=True)


# ── Public fetch functions ────────────────────────────────────────────────────

def fetch_mrp_distribution() -> pd.DataFrame:
    """
    Fetch MRP percentile distribution per category from the Fabric warehouse.
    Used to compute data-driven priceband break points via compute_priceband_breaks().
    """
    conn = connect()
    try:
        print("Fetching MRP distribution per category...")
        df = pd.read_sql(_MRP_DIST_SQL, conn)
        print(f"  {len(df):,} categories fetched.")
        return df
    finally:
        conn.close()


def fetch_eda_dataset(breaks: dict = None) -> pd.DataFrame:
    """
    Fetch style-level data from Fabric, apply per-category priceband classification,
    and aggregate to bucket level (store x category x priceband).

    Parameters
    ----------
    breaks : dict, optional
        Per-category priceband breaks from compute_priceband_breaks().
        When None, loads from data/processed/priceband_config.json if it exists,
        otherwise falls back to uniform defaults (Economy < Rs 2000, Mid < Rs 3000).

    Returns
    -------
    pd.DataFrame
        One row per store-bucket with revenue_rate, sell_through_pct,
        style_count_in_bucket, signal_preview, solver_readiness, and all
        columns the solver and Streamlit app expect.
    """
    # Load breaks from saved config if not supplied
    if breaks is None:
        config_path = Path(__file__).parents[2] / "data" / "processed" / "priceband_config.json"
        if config_path.exists():
            with open(config_path) as fh:
                breaks = json.load(fh).get("breaks", {})
        if not breaks:
            breaks = {"_default": {"economy_cap": 2000, "mid_cap": 3000}}

    conn = connect()
    try:
        print("Fetching style-level EDA data from Fabric...")
        style_df = pd.read_sql(_EDA_SQL, conn)
        print(f"  {len(style_df):,} style rows fetched.")
    finally:
        conn.close()

    print("Applying per-category priceband classification in Python...")
    style_df = _apply_priceband(style_df, breaks)

    print("Aggregating to bucket level (store x category x priceband)...")
    bucket_df = _aggregate_to_buckets(style_df)
    print(f"  {len(bucket_df):,} store-bucket rows.")

    return bucket_df


# ── CLI entrypoint ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    """
    Two-pass fetch: MRP distribution -> priceband breaks -> EDA dataset.

    Usage:
        python src/data_pipeline/fabric_connector.py

    Outputs (all in data/processed/):
        mrp_distribution_YYYY-MM-DD.csv   — MRP percentiles per category
        priceband_config.json             — per-category break points (used by app)
        priceband_mapping.csv             — human-readable mapping table
        eda_data_YYYY-MM-DD.csv           — bucket-level EDA dataset for solver + app
    """
    import argparse
    from datetime import date

    parser = argparse.ArgumentParser(
        description="Fetch Arrow EDA dataset from Fabric warehouse"
    )
    parser.add_argument(
        "--out-dir",
        default=str(Path(__file__).parents[2] / "data" / "processed"),
        help="Output directory (default: data/processed/)",
    )
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print("  Arrow EDA Dataset Generator")
    print(f"  Warehouse : {WAREHOUSE_SERVER}")
    print(f"  Database  : {WAREHOUSE_DATABASE}")
    print(f"  Output    : {out_dir}/")
    print(f"{'='*60}\n")

    today = date.today().isoformat()

    # ── Step 1: MRP distribution -> data-driven priceband breaks ─────────
    print("Step 1/2  MRP price distribution per category...")
    mrp_df   = fetch_mrp_distribution()
    mrp_path = out_dir / f"mrp_distribution_{today}.csv"
    mrp_df.to_csv(mrp_path, index=False)
    print(f"  Saved: {mrp_path.name}")

    breaks = compute_priceband_breaks(mrp_df)

    # Save JSON config (loaded by app and fetch_eda_dataset)
    config_path = out_dir / "priceband_config.json"
    with open(config_path, "w") as fh:
        json.dump({"generated_on": today, "breaks": breaks}, fh, indent=2)
    print(f"  Priceband config saved: {config_path.name}")

    # Save human-readable CSV mapping
    mapping_rows = [
        {"category": cat, "economy_cap": v["economy_cap"], "mid_cap": v["mid_cap"]}
        for cat, v in sorted(breaks.items())
    ]
    pd.DataFrame(mapping_rows).to_csv(out_dir / "priceband_mapping.csv", index=False)
    print(f"  Priceband mapping CSV saved: priceband_mapping.csv")

    print(f"\n  {'Category':<25} {'Economy cap':>12}  {'Mid cap':>10}")
    print(f"  {'-'*52}")
    for cat, b in sorted((k, v) for k, v in breaks.items() if k != "_default"):
        print(f"  {cat:<25} <= Rs {b['economy_cap']:>6,}  <= Rs {b['mid_cap']:>6,}")
    print(
        f"  {'_default (fallback)':<25} <= Rs "
        f"{breaks['_default']['economy_cap']:>6,}  <= Rs "
        f"{breaks['_default']['mid_cap']:>6,}"
    )

    # ── Step 2: EDA dataset with data-driven pricebands ──────────────────
    print(f"\nStep 2/2  EDA dataset with per-category pricebands...")
    df = fetch_eda_dataset(breaks)

    out_path = out_dir / f"eda_data_{today}.csv"
    df.to_csv(out_path, index=False)

    print(f"\nRows       : {len(df):,}")
    print(f"Stores     : {df['store_id'].nunique():,}")
    print(f"Buckets    : {len(df):,}")
    valid_rate = df["revenue_rate"].notna().sum()
    print(f"Valid rate : {valid_rate:,} / {len(df):,} buckets")
    print(f"Saved      : {out_path}")
    print("\nRun solver next: python src/solver/run_solver.py --store all")
